name: update-bot
run-name: Updating bot

on:
    push:
        tags:
            - 'v*'
        branches: main

jobs:
    send-webhook-to-server:
        runs-on: ubuntu-latest
        steps:
            - name: Send webhook
              uses: distributhor/workflow-webhook@v3
              with:
                  webhook_auth_header: 'header'
                  webhook_url: '${{ secrets.WEBHOOK_URL }}'
                  webhook_secret: '${{ secrets.WEBHOOK_SECRET }}'
